# Generated by Django 2.0.2 on 2018-03-13 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=45)),
                ('os', models.CharField(max_length=45)),
                ('ip_address', models.GenericIPAddressField()),
                ('ram', models.IntegerField(help_text='unit MB')),
                ('cpu', models.IntegerField(help_text='the number of cores')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('issue', models.IntegerField(choices=[(0, 'Schedule'), (1, 'Warning'), (2, 'Error')])),
            ],
            options={
                'ordering': ('email',),
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('computer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Computer')),
            ],
            options={
                'ordering': ('timestamp',),
            },
        ),
        migrations.CreateModel(
            name='Sync',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_time', models.DateTimeField()),
                ('capacity_used', models.FloatField()),
            ],
            options={
                'ordering': ('sync_time',),
            },
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(help_text='HDD or SSD', max_length=10)),
                ('capacity', models.IntegerField(help_text='unit GB')),
                ('vendor', models.CharField(max_length=200)),
                ('speed', models.IntegerField(help_text='unit rpm')),
                ('computer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Computer')),
            ],
        ),
        migrations.AddField(
            model_name='sync',
            name='volume',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Volume'),
        ),
    ]
