# Generated by Django 2.0.2 on 2018-08-17 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=45)),
                ('platform', models.CharField(blank=True, max_length=100, null=True)),
                ('ram', models.FloatField(blank=True, help_text='Unit GB', null=True)),
                ('cpu', models.IntegerField(blank=True, help_text='The number of CPU cores', null=True)),
                ('allowed_capacity', models.FloatField(default=50)),
                ('token', models.CharField(max_length=40)),
                ('key', models.CharField(max_length=44)),
                ('status', models.BooleanField(default=True, help_text='set True to enable backup and vice versa')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('issue', models.IntegerField(choices=[(0, 'Schedule'), (1, 'Warning'), (2, 'Error')])),
            ],
            options={
                'ordering': ('email',),
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('typeofbackup', models.IntegerField(choices=[(0, 'Once'), (1, 'Daily'), (2, 'Weekly')])),
                ('status', models.IntegerField(choices=[(0, 'Done'), (1, 'Progressing...'), (2, 'Pending...'), (3, 'Stop')], default=2)),
                ('ip_server', models.CharField(max_length=21)),
                ('path', models.CharField(max_length=1000)),
                ('computer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Computer')),
            ],
        ),
        migrations.CreateModel(
            name='Sync',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_time', models.DateTimeField()),
                ('amount_data_change', models.FloatField()),
                ('path', models.CharField(max_length=1000)),
                ('ip_server', models.CharField(max_length=21)),
                ('status', models.CharField(max_length=100)),
                ('computer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Computer')),
            ],
            options={
                'ordering': ('-sync_time',),
            },
        ),
    ]
