# Generated by Django 2.0.2 on 2018-07-08 15:17

from django.db import migrations, models
import django.db.models.deletion
import versionfield


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=45)),
                ('os', models.CharField(blank=True, max_length=45, null=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('agent_version', versionfield.VersionField(default='1.0.0')),
                ('ram', models.IntegerField(blank=True, help_text='Unit MB', null=True)),
                ('cpu', models.IntegerField(blank=True, help_text='The number of CPU cores', null=True)),
                ('allowed_capacity', models.FloatField(default=50)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('issue', models.IntegerField(choices=[(0, 'Schedule'), (1, 'Warning'), (2, 'Error')])),
            ],
            options={
                'ordering': ('email',),
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('typeofbackup', models.IntegerField(choices=[(0, 'Once'), (1, 'Daily'), (2, 'Weekly'), (3, 'Monthly')])),
                ('status', models.BooleanField(default=False)),
                ('ip_server', models.CharField(max_length=15)),
                ('path', models.CharField(max_length=1000)),
                ('computer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Computer')),
            ],
        ),
        migrations.CreateModel(
            name='Sync',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_time', models.DateTimeField()),
                ('amount_data_change', models.FloatField()),
                ('computer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Computer')),
            ],
            options={
                'ordering': ('-sync_time',),
            },
        ),
    ]
