# Generated by Django 2.0.2 on 2018-08-22 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestoreJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=1000)),
                ('time', models.DateTimeField()),
                ('status', models.IntegerField(choices=[(0, 'Done'), (1, 'Progressing...'), (2, 'Pending...'), (3, 'Cancel')], default=2)),
                ('computer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Computer')),
            ],
        ),
        migrations.AlterField(
            model_name='sync',
            name='amount_data_change',
            field=models.FloatField(help_text='Unit MB'),
        ),
    ]
