# Generated by Django 2.0.2 on 2018-08-24 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restorejob',
            name='status_text',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
    ]
