# Generated by Django 2.0.2 on 2018-03-13 13:19

from django.db import migrations, models
import versionfield


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='agent_version',
            field=versionfield.VersionField(default='0.0.0'),
        ),
        migrations.AddField(
            model_name='computer',
            name='cpus',
            field=models.IntegerField(default=0),
        ),
    ]
