# Generated by Django 2.0.2 on 2018-08-24 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_restorejob_status_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restorejob',
            name='status_text',
        ),
        migrations.AlterField(
            model_name='restorejob',
            name='status',
            field=models.IntegerField(choices=[(0, 'Done'), (1, 'Progressing...'), (2, 'Pending...'), (3, 'Cancel'), (4, 'Error')], default=2),
        ),
    ]
