# Generated by Django 2.0.2 on 2018-07-09 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180709_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='ip_server',
            field=models.CharField(max_length=21),
        ),
    ]
