# Generated by Django 2.0.2 on 2018-08-24 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180824_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.IntegerField(choices=[(0, 'Done'), (1, 'Progressing...'), (2, 'Pending...'), (3, 'Stop'), (4, 'Error')], default=2),
        ),
    ]
