# Generated by Django 2.0.2 on 2018-07-14 17:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180709_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='key',
            field=models.CharField(default=django.utils.timezone.now, max_length=44),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='computer',
            name='token',
            field=models.CharField(default=datetime.datetime(2018, 7, 14, 17, 53, 59, 134912, tzinfo=utc), max_length=40),
            preserve_default=False,
        ),
    ]
