# Generated by Django 2.0.2 on 2018-08-04 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180714_2153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='computer',
            old_name='os',
            new_name='platform',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='agent_version',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='ip_address',
        ),
        migrations.AlterField(
            model_name='computer',
            name='ram',
            field=models.FloatField(blank=True, help_text='Unit GB', null=True),
        ),
    ]
