# Generated by Django 2.0.2 on 2018-08-04 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180804_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='platform',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
