# Generated by Django 2.0.2 on 2018-08-04 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20180804_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='computer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Computer'),
        ),
        migrations.AlterField(
            model_name='sync',
            name='computer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Computer'),
        ),
    ]
